name: Build and Upload Rust App

on:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
      - 'web/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.77.0

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build application
      run: cargo build --release --verbose
    
    - name: Prepare output directory
      run: |
        mkdir output
        copy target\release\forlenza-scada.exe output\ForlenzaScada.exe

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: forlenza-scada-${{ github.sha }}
        path: target/release/forlenza-scada.exe
        retention-days: 30

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local-dir: output/
        server-dir: /htdocs/downloads/